version: 2.1

# parameters:
#   GHA_Event:
#     type: string
#     default: ""
#   GHA_Actor:
#     type: string
#     default: ""
#   GHA_Action:
#     type: string
#     default: ""
#   GHA_Meta:
#     type: string
#     default: ""

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            gem install rake
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - configure_bundler

  # rubocop:
  #   docker:
  #     - image: circleci/ruby:3.0.0-node-browsers-legacy
  #   steps:
  #     - checkout
  #     - configure_bundler
  #     - run:
  #         name: Rubocop
  #         command: bundle exec rubocop
  # deploy:
  #   docker:
  #     - image: circleci/ruby:3.0.0

  #   steps:
  #     - checkout
  #     - run:
  #         name: deploy app to heroku
  #         command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build:
    jobs:
      - build

  # deploy:
  #   when: << pipeline.parameters.GHA_Action >>
  #   jobs:
  #     - deploy
